### ISSUE TITLE
which input fast5

### ISSUE THREAD

**Issue by sdwien** [enovoa/EpiNano#13]
What sort of fast5 files is expected as an input for the 
`python2 fast5ToEventTbl.py input.fast5 > output.event.tbl`
step?
I was trying to use both single and multi read fast5 files, generated from a MinION direct RNA seq run, both without (directly from the sequencing run w/o live base calling) and with basecalling (after guppy) information inside, but they all fail with an error, e.g.:

```
Traceback (most recent call last):
  File "fast5ToEventTbl.py", line 45, in <module>
    main()

  File "fast5ToEventTbl.py", line 29, in main
    read_id = get_readid(f5)

  File "fast5ToEventTbl.py", line 16, in get_readid
    k = h5['Raw/Reads/'].keys()[0]

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5o.pyx", line 190, in h5py.h5o.open

KeyError: 'Unable to open object (component not found)'

```
I looked at the fast5ToEventTbl.py script and see that it goes for the Analyses section of the fast5 file. I do have this section, and I also have a section inside this called Basecall_1D_000, e.g.:

```
GROUP "Analyses" {
     
 GROUP "Basecall_1D_000" {
         
GROUP "BaseCalled_template" {
            
DATASET "Fastq" {
             
  DATATYPE  H5T_STRING {
                 
 STRSIZE H5T_VARIABLE;
                 
 STRPAD H5T_STR_NULLTERM;
                 
 CSET H5T_CSET_UTF8;
                  
CTYPE H5T_C_S1;
              
 }
              
 DATASPACE  SCALAR
              
 DATA {
              
 (0): "@ffaca199-6d26-4d6f-96f3-9180aed3de4d runid=7fa1e1733fdb76c8e61f4b217a6bf781257cd601 sampleid=3T3L1_0hours read=22926 ch=129 start_time=2019-05-03T20:54:16Z
           
CUGCAGUUGGUUGCGAAGUCUUCCAUCCCUCUAGACGAAGCCUUGGGAUGAUGAGAGACGGACAUGACAAACUAGAGGAGUGUGUCCGAAGCAUUCAGAUGGCCUGGUGUGUGGGGCUCCUAAAUUGGUUCCAGUGGGAUAUGGAAUUAAAAGCAAGGAAGCUUCAAAUACAGUGUGGUUGAAGAUGAUAAGGUUGGAACGGAUAUGGAAGAGCAAAUUGCUUUGAGGACUACGUCUACAGUCCAUUGGAUGUGGCUGCUUCUUAACAAGAUUUAAAUCAUCUUAAGUCAGUGCACUUAAAUAAAAGCUUGAAAGAUAGU
         
  +
          
 8:79;?761/074*6@E52-&&*('+3<+/)89B0';?@9::7:88F<<C===4?6;B*@BD6?<60)+,<>33;9?/#-?=::558>JH8=7-$#.AD380166;;0$&99&<=61*.388;0417805,61A528A:;43@@9:6:::982+&).-,*75&)20:1836/A47/.)76)=GEC9DF=EG=;96-?;-3/=;.$#+7GFG=B=:-%&804/*89,7:6.*417'$()277:91/$$(98:=-,21--'+,#-.ABBABA>>9=32(-&&'$'455A44491>'(1*345'25789+++.60/3;&%$%#
```

One of the fast5 files from the "modified" folder in the /examples folder worked successfully. I believe those are single read fast5 files, is that right? How did you generate them?

Many thanks for your help over again, best, Sophia

**Comment by Huanle** [comment]
@sdwien , sorry for the late reply.
Yes, the example fast5 files are single read fast5 files. They were basecalled with albacore version 2.7.1.
I will add a raw current extraction script for multi-reads fast5 files. 
Please feel free to send your example fast5 file.

**Comment by sdwien** [comment]
Hi @Huanle
I sent you an example file to your crg email address.
Thanks a lot for looking into this.

**Comment by Huanle** [comment]
Hi @sdwien ,
Thanks for sending it through. But i haven't received it yet.
Will you re-send it again to huanle.liu@crg.eu ?
Thanks again.

**Comment by s-t-calus** [comment]
Hello @Huanle

Did you manage to fix that problem? I'm getting the same error, I can send you a file if needed?

Regards
s-t-c

**Comment by Huanle** [comment]
Hi @s-t-calus ,
You need a fasst5 with basecalling information generated with Albacore. 
Basically, there has to be an event table in the fast5 file to be extracted. 
Otherwise, you can still continue your analyses without including the current intensity feature.
Hope this helps.

**Comment by s-t-calus** [comment]
I used real-time basecalling with MinKNOW I also have Guppy installed on the server, can I use any of them or albacore is specifically required?
