### ISSUE TITLE
Unable to run fast5ToEventTbl.py

### ISSUE THREAD

**Issue by hygine** [enovoa/EpiNano#6]
Hi, I'm trying to use fast5ToEventTbl.py to call my ONT RNA Meth, but for some reason I am unable to run correctly fast5ToEventTbl.py.

I tried to run it with that command:

`python2 ./fast5ToEventTbl.py ./my_data/xxx1.fast5  > ./my_data/output.event.tbl`

And I got that error for every fast5 in my test folder:
`Traceback (most recent call last):
  File "./scripts/main/fast5ToEventTbl.py", line 44, in <module>
    main()
  File "./scripts/main/fast5ToEventTbl.py", line 30, in main
    base_call = get_base_call_path(f5)
  File "./scripts/main/fast5ToEventTbl.py", line 22, in get_base_call_path
    for i in list (h5['Analyses/'].keys()):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/lustre/nas1/wenyh/ONT/software/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Analyses' doesn't exist)"
`
I am on CentOS release 6.5 (Final) and I believe all the dependencies are up to date.

I also tried to use other set of fast5 files coming from another run but the error remained.
I thank you in advance for any help. @Huanle @enovoa 

Hygine

**Comment by enovoa** [comment]
Can you please test on fast5 examples included in the github release? Thanks

**Comment by Huanle** [comment]
@hygine Or can you share with me one of your fast5 files?

**Comment by s-t-calus** [comment]
Hello  @Huanle 

I used:
(/software/epinano-v1.1) [stc@sgpu EpiNano_Analysis]$ python2 /software/epinano-v1.1/EpiNano-1.1/scripts/main/fast5ToEventTbl.py ../FAST5/FAL28539_7e6187f58ebf04fcfbeaff14d7126db562a28ee0_100.fast5 > output.event.tbl

But got an error:

Traceback (most recent call last)
I keep getting error

Traceback (most recent call last):
  File "/software/epinano-v1.1/EpiNano-1.1/scripts/main/fast5ToEventTbl.py", line 45, in <module>
    main()
  File "/software/epinano-v1.1/EpiNano-1.1/scripts/main/fast5ToEventTbl.py", line 29, in main
    read_id = get_readid(f5)
  File "/software/epinano-v1.1/EpiNano-1.1/scripts/main/fast5ToEventTbl.py", line 16, in get_readid
    k = h5['Raw/Reads/'].keys()[0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/software/epinano-v1.1/python2-sub-env/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'

Downloaded your test file and have the same issue, any idea what's the reason?

Regards
s-t-c
