### ISSUE TITLE
Issue running Epinano_Variants.py

### ISSUE THREAD

**Issue by cednotsed** [enovoa/EpiNano#60]
With reference to a previously closed [issue](https://github.com/enovoa/EpiNano/issues/55#issuecomment-693796149), I am facing the same problem running Epinano_Variants. 

```
Process Process-2:
Traceback (most recent call last):
  File "/home/cedrict/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/cedrict/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/hgst8TB/csctan/EpiNano/epinano_modules.py", line 187, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration
```
However, like @eliah-o, I had no luck getting the script to work despite trying out the python virtual environment you suggested nor with downgrading pandas to 0.24.2.

Please advise. Thanks.

**Comment by Huanle** [comment]
Hi @cednotsed ,
Did you get any output(s)?

Can you list the pkgs you've installed?
```
pip list
```

**Comment by cednotsed** [comment]
Package         Version 
--------------- --------
dask            2.28.0  
fsspec          0.8.3   
locket          0.2.0   
numpy           1.19.2  
pandas          0.25.1  
partd           1.1.0   
pip             18.1    
pysam           0.16.0.1
python-dateutil 2.8.1   
pytz            2020.1  
PyYAML          5.3.1   
setuptools      40.6.2  
six             1.15.0  
toolz           0.11.1  


I did not get any output except an empty tmp directory.

**Comment by Huanle** [comment]
Hi @cednotsed ,

Can you try commands below and let me know whether it works?

```
python3.8 -m venv epinano12_py38 # py38  can avoid issues associated with process communication via pickled data 
source epinano12_py38/bin/activate
pip install pandas
pip install  dask==2.5.2
python -m pip install "dask[dataframe]"
pip install pysam
```

**Comment by cednotsed** [comment]
Process Process-2:
Traceback (most recent call last):
  File "/home/cedrict/miniconda3/envs/py3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/cedrict/miniconda3/envs/py3.8.3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/hgst8TB/csctan/EpiNano/epinano_modules.py", line 187, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration

**Comment by cednotsed** [comment]
Package         Version 
--------------- --------
cloudpickle     1.6.0   
dask            2.5.2   
fsspec          0.8.3   
locket          0.2.0   
numpy           1.19.2  
pandas          1.1.2   
partd           1.1.0   
pip             19.2.3  
pysam           0.16.0.1
python-dateutil 2.8.1   
pytz            2020.1  
setuptools      41.2.0  
six             1.15.0  
toolz           0.11.1 


/hgst8TB/csctan/RNA_modifications/epinano12_py38/lib/python3.8/site-packages/dask/dataframe/utils.py:14: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
data/epinano_rna/raw_files/nomod_rep1/nomod_rep1.tmp_splitted already exists, will overwrite it
Process Process-2:
Traceback (most recent call last):
  File "/home/cedrict/miniconda3/envs/py3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/cedrict/miniconda3/envs/py3.8.3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/hgst8TB/csctan/EpiNano/epinano_modules.py", line 187, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration

**Comment by Huanle** [comment]
Hi @cednotsed ，

Did you get any output?
Do you mind sharing with me some of your input data, like a bam and reference sequences？
Thanks.

**Comment by Huanle** [comment]
Hi @cednotsed ,
Can you try with the latest Epinano_Variants.py and let me know whether it works?
