### ISSUE TITLE
run Epinano_Variants.py failed

### ISSUE THREAD

**Issue by xthua** [enovoa/EpiNano#86]
Hi, 
When I run Epinano_Variants.py, I met the followed message:

Process Process-2:
Traceback (most recent call last):
  File "/data/soft_install/envs/epinano2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/soft_install/envs/epinano2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/soft/epinano/EpiNano-Epinano1.2.0/epinano_modules.py", line 187, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration

**Comment by JeremyQuo** [comment]
Hi,it comes the same error as you.
Can you tell me how to solve it please?
